import palette from './palette.js';


const settings = {
    // general
    "descriptionForeground": palette.typography.body,
    "errorForeground": null,
    "focusBorder": palette.transparent,
    "foreground": palette.typography.subtitle,
    "icon.foreground": palette.typography.subtitle,
    "progressBar.background": palette.general.accent,
    "sash.hoverBorder": palette.general.border,
    "selection.background": null,
    "widget.shadow": palette.general.shadow,
    // text
    "textBlockQuote.background": null,
    "textBlockQuote.border": null,
    "textCodeBlock.background": null,
    "textLink.activeForeground": palette.typography.accent,
    "textLink.foreground": palette.typography.accent,
    "textPreformat.foreground": null,
    "textSeparator.foreground": null,
    // menu
    "menu.background": palette.general.base,
    "menu.border": palette.general.border,
    "menu.foreground": palette.typography.body,
    "menu.selectionBackground": null,
    "menu.selectionBorder": null,
    "menu.selectionForeground": null,
    "menu.separatorBackground": null,
    "menubar.selectionBackground": null,
    "menubar.selectionBorder": null,
    "menubar.selectionForeground": null,
    // title bar
    "titleBar.activeBackground": palette.general.base,
    "titleBar.activeForeground": palette.typography.title,
    "titleBar.inactiveBackground": palette.general.base,
    "titleBar.inactiveForeground": palette.typography.title,
    // command center
    "commandCenter.activeBackground": palette.general.surface,
    "commandCenter.activeForeground": palette.typography.subtitle,
    "commandCenter.background": palette.general.surface,
    "commandCenter.border": palette.general.border,
    "commandCenter.foreground": palette.typography.subtitle,
    // welcome page
    "walkThrough.embeddedEditorBackground": null,
    "welcomePage.background": palette.general.base,
    "welcomePage.progress.background": null,
    "welcomePage.progress.foreground": null,
    "welcomePage.tileBackground": null,
    "welcomePage.tileHoverBackground": null,
    "welcomePage.tileShadow": palette.general.shadow,
    // activity bar - general
    "activityBar.background": palette.general.base,
    "activityBar.border": palette.general.border,
    "activityBar.dropBorder": palette.general.border,
    "activityBar.foreground": palette.general.accent,
    "activityBar.inactiveForeground": palette.typography.subtitle,
    // activity bar - active item
    "activityBar.activeBackground": palette.transparent,
    "activityBar.activeBorder": palette.general.accent,
    "activityBar.activeFocusBorder": palette.transparent,
    // activity bar - badges
    "activityBarBadge.background": palette.general.accent02,
    "activityBarBadge.foreground": palette.typography.contrast,
    // sidebar - general
    "sideBar.background": palette.general.base,
    "sideBar.border": palette.general.border,
    "sideBar.dropBackground": null,
    "sideBar.foreground": palette.typography.body,
    // sidebar - titles/headers
    "sideBarSectionHeader.background": palette.general.base,
    "sideBarSectionHeader.border": palette.general.border,
    "sideBarSectionHeader.foreground": palette.typography.subtitle,
    "sideBarTitle.foreground": palette.typography.title,
    // status bar - general
    "statusBar.background": palette.general.base,
    "statusBar.foreground": palette.typography.body,
    "statusBar.border": palette.transparent,
    "statusBar.debuggingBackground": palette.general.base,
    "statusBar.debuggingForeground": palette.typography.body,
    "statusBar.noFolderBackground": palette.general.base,
    "statusBar.noFolderForeground": palette.typography.body,
    // status bar - items
    "statusBarItem.activeBackground": null,
    "statusBarItem.hoverBackground": null,
    "statusBarItem.remoteBackground": null,
    "statusBarItem.remoteForeground": null,
    "statusBar.focusBorder": palette.transparent,
    "statusBarItem.compactHoverBackground": null,
    "statusBarItem.errorBackground": null,
    "statusBarItem.errorForeground": null,
    "statusBarItem.focusBorder": palette.transparent,
    "statusBarItem.prominentBackground": null,
    "statusBarItem.prominentForeground": null,
    "statusBarItem.prominentHoverBackground": null,
    "statusBarItem.warningBackground": null,
    "statusBarItem.warningForeground": null,
    // tabs - general
    "tab.border": palette.general.border,
    "tab.hoverBackground": palette.general.base,
    "tab.hoverBorder": palette.general.border,
    "tab.hoverForeground": palette.typography.title,
    "tab.lastPinnedBorder": palette.general.border,
    // tabs - active/inactive
    "tab.activeBackground": palette.general.base,
    "tab.activeBorder": palette.general.border,
    "tab.activeBorderTop": palette.general.border,
    "tab.activeForeground": palette.typography.title,
    "tab.activeModifiedBorder": null,
    "tab.inactiveBackground": palette.general.base,
    "tab.inactiveForeground": palette.typography.subtitle,
    "tab.inactiveModifiedBorder": null,
    // tabs - unfocused active/inactive
    "tab.unfocusedActiveBackground": null,
    "tab.unfocusedActiveBorder": null,
    "tab.unfocusedActiveBorderTop": null,
    "tab.unfocusedActiveForeground": null,
    "tab.unfocusedActiveModifiedBorder": null,
    "tab.unfocusedInactiveBackground": null,
    "tab.unfocusedInactiveForeground": null,
    "tab.unfocusedInactiveModifiedBorder": null,
    // tabs - unfocused hover
    "tab.unfocusedHoverBackground": null,
    "tab.unfocusedHoverBorder": null,
    "tab.unfocusedHoverForeground": null,
    // editor - general
    "editor.background": palette.general.base,
    "editor.foldBackground": null,
    "editor.foreground": palette.typography.body,
    "editor.lineHighlightBackground": null,
    "editor.lineHighlightBorder": null,
    "editorCursor.background": null,
    "editorCursor.foreground": null,
    "editorIndentGuide.activeBackground": palette.typography.body,
    "editorIndentGuide.background": palette.typography.obscure,
    "editorLineNumber.activeForeground": palette.typography.body,
    "editorLineNumber.foreground": palette.typography.obscure,
    "editorLink.activeForeground": null,
    "editorPane.background": palette.general.base,
    "editorRuler.foreground": null,
    "editorWhitespace.foreground": palette.general.border,
    // editor - gutter
    "editorGutter.addedBackground": null,
    "editorGutter.background": palette.general.base,
    "editorGutter.deletedBackground": null,
    "editorGutter.foldingControlForeground": palette.general.border,
    "editorGutter.modifiedBackground": null,
    // editor - status info
    "editorError.foreground": null,
    "editorInfo.foreground": null,
    "editorWarning.foreground": null,
    "problemsErrorIcon.foreground": null,
    "problemsInfoIcon.foreground": null,
    "problemsWarningIcon.foreground": null,
    // editor - lightbulb
    "editorLightBulb.foreground": null,
    "editorLightBulbAutoFix.foreground": null,
    // editor - overview ruler
    "editorOverviewRuler.addedForeground": null,
    "editorOverviewRuler.background": palette.general.base,
    "editorOverviewRuler.border": palette.general.border,
    "editorOverviewRuler.bracketMatchForeground": null,
    "editorOverviewRuler.deletedForeground": null,
    "editorOverviewRuler.errorForeground": null,
    "editorOverviewRuler.findMatchForeground": null,
    "editorOverviewRuler.infoForeground": null,
    "editorOverviewRuler.modifiedForeground": null,
    "editorOverviewRuler.rangeHighlightForeground": null,
    "editorOverviewRuler.selectionHighlightForeground": null,
    "editorOverviewRuler.warningForeground": null,
    "editorOverviewRuler.wordHighlightForeground": null,
    "editorOverviewRuler.wordHighlightStrongForeground": null,
    // editor - selection
    "editor.inactiveSelectionBackground": null,
    "editor.selectionBackground": null,
    "editor.selectionForeground": null,
    "editor.selectionHighlightBackground": null,
    "editor.selectionHighlightBorder": null,
    // editor - brackets
    "editorBracketMatch.background": null,
    "editorBracketMatch.border": palette.general.border,
    // editor - bracket pair colorization
    "editorBracketHighlight.foreground1": null,
    "editorBracketHighlight.foreground2": null,
    "editorBracketHighlight.foreground3": null,
    "editorBracketHighlight.foreground4": null,
    "editorBracketHighlight.foreground5": null,
    "editorBracketHighlight.foreground6": null,
    // editor - bracket pair guides
    "editorBracketPairGuide.activeBackground1": null,
    "editorBracketPairGuide.activeBackground2": null,
    "editorBracketPairGuide.activeBackground3": null,
    "editorBracketPairGuide.activeBackground4": null,
    "editorBracketPairGuide.activeBackground5": null,
    "editorBracketPairGuide.activeBackground6": null,
    "editorBracketPairGuide.background1": null,
    "editorBracketPairGuide.background2": null,
    "editorBracketPairGuide.background3": null,
    "editorBracketPairGuide.background4": null,
    "editorBracketPairGuide.background5": null,
    "editorBracketPairGuide.background6": null,
    // editor - occurence highlight
    "editor.findMatchBackground": null,
    "editor.findMatchBorder": null,
    "editor.findMatchHighlightBackground": null,
    "editor.findMatchHighlightBorder": null,
    "editor.hoverHighlightBackground": null,
    "editor.wordHighlightBackground": null,
    "editor.wordHighlightBorder": null,
    "editor.wordHighlightStrongBackground": null,
    "editor.wordHighlightStrongBorder": null,
    // editor - inline hints
    "editorInlayHint.background": null,
    "editorInlayHint.foreground": null,
    "editorInlayHint.parameterBackground": null,
    "editorInlayHint.parameterForeground": null,
    "editorInlayHint.typeBackground": null,
    "editorInlayHint.typeForeground": null,
    // editor - snippets
    "editor.snippetFinalTabstopHighlightBackground": null,
    "editor.snippetTabstopHighlightBackground": null,
    // breadcrumbs
    "breadcrumb.activeSelectionForeground": null,
    "breadcrumb.background": palette.general.base,
    "breadcrumb.focusForeground": palette.typography.body,
    "breadcrumb.foreground": palette.typography.body,
    "breadcrumbPicker.background": palette.general.base,
    // minimap
    "minimap.background": palette.general.base,
    "minimap.errorHighlight": null,
    "minimap.findMatchHighlight": null,
    "minimap.foregroundOpacity": null,
    "minimap.selectionHighlight": null,
    "minimap.selectionOccurrenceHighlight": null,
    "minimap.warningHighlight": null,
    "minimapGutter.addedBackground": null,
    "minimapGutter.deletedBackground": null,
    "minimapGutter.modifiedBackground": null,
    "minimapSlider.activeBackground": null,
    "minimapSlider.background": null,
    "minimapSlider.hoverBackground": null,
    // panel - general
    "panel.background": palette.general.base,
    "panel.border": palette.general.border,
    "panel.dropBorder": palette.general.border,
    "panelInput.border": palette.general.border,
    // panel - section
    "panelSection.border": palette.general.border,
    "panelSection.dropBackground": null,
    "panelSectionHeader.background": null,
    "panelSectionHeader.border": palette.general.border,
    "panelSectionHeader.foreground": null,
    // panel - title
    "panelTitle.activeBorder": null,
    "panelTitle.activeForeground": null,
    "panelTitle.inactiveForeground": palette.typography.subtitle,
    // terminal - general
    "terminal.background": palette.general.base,
    "terminal.border": palette.general.border,
    "terminal.dropBackground": null,
    "terminal.foreground": palette.typography.body,
    "terminal.tab.activeBorder": null,
    "terminalCursor.background": null,
    "terminalCursor.foreground": null,
    // terminal - colors
    "terminal.ansiBlack": palette.typography.title,
    "terminal.ansiBlue": null,
    "terminal.ansiBrightBlack": null,
    "terminal.ansiBrightBlue": null,
    "terminal.ansiBrightCyan": null,
    "terminal.ansiBrightGreen": null,
    "terminal.ansiBrightMagenta": null,
    "terminal.ansiBrightRed": null,
    "terminal.ansiBrightWhite": null,
    "terminal.ansiBrightYellow": null,
    "terminal.ansiCyan": null,
    "terminal.ansiGreen": null,
    "terminal.ansiMagenta": null,
    "terminal.ansiRed": null,
    "terminal.ansiWhite": null,
    "terminal.ansiYellow": null,
    // terminal - selection
    "terminal.selectionBackground": null,
    "terminal.selectionForeground": null,
    // terminal - occurence highlight
    "terminal.findMatchBackground": null,
    "terminal.findMatchBorder": null,
    "terminal.findMatchHighlightBackground": null,
    "terminal.findMatchHighlightBorder": null,
    // terminal - overview ruler
    "terminalOverviewRuler.cursorForeground": null,
    "terminalOverviewRuler.findMatchForeground": null,
    // terminal - command decoration
    "terminalCommandDecoration.defaultBackground": null,
    "terminalCommandDecoration.errorBackground": null,
    "terminalCommandDecoration.successBackground": null,
    // editor widgets - general
    "editorWidget.background": palette.general.base,
    "editorWidget.border": palette.general.border,
    "editorWidget.foreground": palette.typography.body,
    "editorWidget.resizeBorder": null,
    // editor widgets - hover
    "editorHoverWidget.background": palette.general.base,
    "editorHoverWidget.border": palette.general.border,
    "editorHoverWidget.foreground": palette.typography.body,
    "editorHoverWidget.highlightForeground": null,
    "editorHoverWidget.statusBarBackground": palette.general.base,
    // editor widgets - suggestions
    "editorSuggestWidget.background": palette.general.base,
    "editorSuggestWidget.border": palette.general.border,
    "editorSuggestWidget.foreground": palette.typography.body,
    "editorSuggestWidget.highlightForeground": null,
    "editorSuggestWidget.focusHighlightForeground": null,
    "editorSuggestWidget.selectedBackground": palette.general.base,
    "editorSuggestWidget.selectedForeground": null,
    "editorSuggestWidget.selectedIconForeground": null,
    "editorSuggestWidgetStatus.foreground": palette.typography.body,
    // editor groups - general
    "editorGroup.border": palette.general.border,
    "editorGroup.dropBackground": null,
    "editorGroup.emptyBackground": palette.general.base,
    // editor groups - header
    "editorGroupHeader.noTabsBackground": palette.general.base,
    "editorGroupHeader.tabsBackground": palette.general.base,
    // editor groups - drop-in prompt
    "editorGroup.dropIntoPromptBackground": null,
    "editorGroup.dropIntoPromptBorder": null,
    "editorGroup.dropIntoPromptForeground": null,
    "editorGroup.focusedEmptyBorder": null,
    // editor groups - side-side border
    "sideBySideEditor.horizontalBorder": palette.general.border,
    "sideBySideEditor.verticalBorder": palette.general.border,
    // list & trees - general
    "list.deemphasizedForeground": null,
    "list.dropBackground": null,
    "list.highlightForeground": null,
    "tree.indentGuidesStroke": null,
    // lists & trees - active/inactive selected
    "list.activeSelectionBackground": palette.editor.currentLineHighlight,
    "list.activeSelectionForeground": palette.typography.title,
    "list.inactiveSelectionBackground": null,
    "list.inactiveSelectionForeground": null,
    // lists & trees - hover
    "list.hoverBackground": null,
    "list.hoverForeground": null,
    // list & trees - information
    "list.errorForeground": null,
    "list.invalidItemForeground": null,
    "list.warningForeground": null,
    // list & trees - filter match
    "list.filterMatchBackground": null,
    "list.filterMatchBorder": null,
    // list & trees - focus
    "list.focusBackground": null,
    "list.focusForeground": null,
    "list.focusHighlightForeground": null,
    "list.inactiveFocusBackground": null,
    // list & trees - filter widget
    "listFilterWidget.background": null,
    "listFilterWidget.noMatchesOutline": null,
    "listFilterWidget.outline": null,
    // list & trees - tree
    "tree.tableColumnsBorder": null,
    "tree.tableOddRowsBackground": null,
    // dif editor
    "diffEditor.border": palette.general.border,
    "diffEditor.diagonalFill": palette.general.border,
    "diffEditor.insertedLineBackground": null,
    "diffEditor.insertedTextBackground": null,
    "diffEditor.insertedTextBorder": null,
    "diffEditor.removedLineBackground": null,
    "diffEditor.removedTextBackground": null,
    "diffEditor.removedTextBorder": null,
    // dif editor - gutter
    "diffEditorGutter.insertedLineBackground": null,
    "diffEditorGutter.removedLineBackground": null,
    "diffEditorOverview.insertedForeground": null,
    "diffEditorOverview.removedForeground": null,
    "searchEditor.findMatchBackground": null,
    "searchEditor.findMatchBorder": null,
    "searchEditor.textInputBorder": null,
    // peek view - general
    "peekView.border": palette.general.border,
    "peekViewEditor.background": palette.general.base,
    "peekViewEditor.matchHighlightBackground": null,
    "peekViewEditor.matchHighlightBorder": null,
    "peekViewEditorGutter.background": palette.general.base,
    // peek view editor - results
    "peekViewResult.background": palette.general.base,
    "peekViewResult.fileForeground": null,
    "peekViewResult.lineForeground": palette.typography.body,
    "peekViewResult.matchHighlightBackground": null,
    "peekViewResult.selectionBackground": palette.general.base,
    "peekViewResult.selectionForeground": null,
    // peek view editor - title
    "peekViewTitle.background": palette.general.base,
    "peekViewTitleDescription.foreground": palette.typography.body,
    "peekViewTitleLabel.foreground": palette.typography.title,
    // quick picker
    "pickerGroup.border": palette.general.border,
    "pickerGroup.foreground": null,
    "quickInput.background": palette.general.base,
    "quickInput.foreground": palette.typography.body,
    "quickInputList.focusBackground": palette.general.base,
    "quickInputList.focusForeground": null,
    "quickInputList.focusIconForeground": null,
    "quickInputTitle.background": null,
    // notifications
    "notificationCenter.border": palette.general.border,
    "notificationCenterHeader.foreground": palette.typography.title,
    "notificationCenterHeader.background": palette.general.base,
    "notificationToast.border": palette.general.border,
    "notifications.foreground": palette.typography.body,
    "notifications.background": palette.general.base,
    "notifications.border": palette.general.border,
    "notificationLink.foreground": null,
    // notifications - status info
    "notificationsErrorIcon.foreground": null,
    "notificationsWarningIcon.foreground": null,
    "notificationsInfoIcon.foreground": null,
    // banner
    "banner.background": palette.general.base,
    "banner.foreground": palette.typography.body,
    "banner.iconForeground": null,
    // settings - general
    "settings.focusedRowBackground": null,
    "settings.focusedRowBorder": null,
    "settings.modifiedItemIndicator": null,
    "settings.rowHoverBackground": null,
    "settings.sashBorder": palette.general.border,
    // settings - header
    "settings.headerBorder": palette.general.border,
    "settings.headerForeground": palette.typography.title,
    // settings - checkbox input
    "settings.checkboxBackground": null,
    "settings.checkboxBorder": palette.general.border,
    "settings.checkboxForeground": palette.typography.body,
    // settings - dropdown input
    "settings.dropdownBackground": palette.general.base,
    "settings.dropdownBorder": palette.general.border,
    "settings.dropdownForeground": palette.typography.body,
    "settings.dropdownListBorder": palette.general.border,
    // settings - number input
    "settings.numberInputBackground": palette.general.base,
    "settings.numberInputBorder": palette.general.border,
    "settings.numberInputForeground": palette.typography.body,
    // settings - text input
    "settings.textInputBackground": null,
    "settings.textInputBorder": palette.general.border,
    "settings.textInputForeground": palette.typography.body,
    // extensions
    "extensionBadge.remoteBackground": null,
    "extensionBadge.remoteForeground": null,
    "extensionButton.prominentBackground": null,
    "extensionButton.prominentForeground": palette.general.base,
    "extensionButton.prominentHoverBackground": null,
    "extensionIcon.preReleaseForeground": null,
    "extensionIcon.sponsorForeground": null,
    "extensionIcon.starForeground": null,
    "extensionIcon.verifiedForeground": null,
    // action items
    "toolbar.activeBackground": null,
    "toolbar.hoverBackground": null,
    // badges
    "badge.background": null,
    "badge.foreground": null,
    // buttons
    "button.background": palette.workbench.button,
    "button.border": null,
    "button.foreground": palette.general.base,
    "button.hoverBackground": palette.workbench.buttonHover,
    "button.secondaryBackground": null,
    "button.secondaryForeground": null,
    "button.secondaryHoverBackground": null,
    // checkbox
    "checkbox.background": null,
    "checkbox.border": "#F6F7F800",
    "checkbox.foreground": "#202021",
    // input control
    "input.background": palette.general.surface,
    "input.border": palette.transparent,
    "input.foreground": palette.typography.body,
    "input.placeholderForeground": palette.typography.obscure,
    "inputOption.activeBackground": null,
    "inputOption.activeBorder": palette.transparent,
    "inputOption.activeForeground": palette.typography.title,
    "inputOption.hoverBackground": null,
    // dropdown control
    "dropdown.background": palette.general.base,
    "dropdown.border": palette.general.border,
    "dropdown.foreground": palette.typography.body,
    "dropdown.listBackground": palette.general.base,
    // scrollbar control
    "scrollbar.shadow": null,
    "scrollbarSlider.activeBackground": palette.general.border,
    "scrollbarSlider.background": null,
    "scrollbarSlider.hoverBackground": palette.general.border,
    // input validation
    "inputValidation.errorBackground": palette.general.base,
    "inputValidation.errorBorder": palette.general.border,
    "inputValidation.errorForeground": null,
    "inputValidation.infoBackground": palette.general.base,
    "inputValidation.infoBorder": palette.general.border,
    "inputValidation.infoForeground": null,
    "inputValidation.warningBackground": palette.general.base,
    "inputValidation.warningBorder": palette.general.border,
    "inputValidation.warningForeground": null,
    // git decorations
    "gitDecoration.addedResourceForeground": null,
    "gitDecoration.conflictingResourceForeground": null,
    "gitDecoration.deletedResourceForeground": null,
    "gitDecoration.ignoredResourceForeground": null,
    "gitDecoration.modifiedResourceForeground": null,
    "gitDecoration.renamedResourceForeground": null,
    "gitDecoration.stageDeletedResourceForeground": null,
    "gitDecoration.stageModifiedResourceForeground": null,
    "gitDecoration.submoduleResourceForeground": null,
    "gitDecoration.untrackedResourceForeground": null,
    // keybind labels
    "keybindingLabel.background": palette.general.base,
    "keybindingLabel.border": palette.general.border,
    "keybindingLabel.bottomBorder": palette.general.border,
    "keybindingLabel.foreground": palette.typography.body,
    // keyboard shortcuts table
    "keybindingTable.rowsBackground": palette.general.base,
    "keybindingTable.headerBackground": palette.general.base,
    // charts
    "charts.blue": null,
    "charts.foreground": palette.typography.subtitle,
    "charts.green": null,
    "charts.lines": palette.typography.body,
    "charts.orange": null,
    "charts.purple": null,
    "charts.red": null,
    "charts.yellow": null,
    // symbol icons
    "symbolIcon.arrayForeground": null,
    "symbolIcon.booleanForeground": null,
    "symbolIcon.classForeground": null,
    "symbolIcon.colorForeground": null,
    "symbolIcon.constantForeground": null,
    "symbolIcon.constructorForeground": null,
    "symbolIcon.enumeratorForeground": null,
    "symbolIcon.enumeratorMemberForeground": null,
    "symbolIcon.eventForeground": null,
    "symbolIcon.fieldForeground": null,
    "symbolIcon.fileForeground": null,
    "symbolIcon.folderForeground": null,
    "symbolIcon.functionForeground": null,
    "symbolIcon.interfaceForeground": null,
    "symbolIcon.keyForeground": null,
    "symbolIcon.keywordForeground": null,
    "symbolIcon.methodForeground": null,
    "symbolIcon.moduleForeground": null,
    "symbolIcon.namespaceForeground": null,
    "symbolIcon.nullForeground": null,
    "symbolIcon.numberForeground": null,
    "symbolIcon.objectForeground": null,
    "symbolIcon.operatorForeground": null,
    "symbolIcon.packageForeground": null,
    "symbolIcon.propertyForeground": null,
    "symbolIcon.referenceForeground": null,
    "symbolIcon.snippetForeground": null,
    "symbolIcon.stringForeground": null,
    "symbolIcon.structForeground": null,
    "symbolIcon.textForeground": null,
    "symbolIcon.typeParameterForeground": null,
    "symbolIcon.unitForeground": null,
    "symbolIcon.variableForeground": null,

}

export default settings;